# docker compose to use with devcontainer

version: '3.1'
services:
  pg-db-ws5:
    image: postgres
    container_name: pg-db-ws5
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      datastats:
        ipv4_address: 172.20.0.2

  flask-api:
    image: <your-docker-username>/flask-api # Pulling the image from dockerhub
    # build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - pg-db-ws5
    networks:
      datastats:
        ipv4_address: 172.20.0.3

networks:
  datastats:
    ipam:
      config:
        - subnet: 172.20.0.0/16