name: Push to Dockerhub
on: push
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        env:
          MY_SECRET: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: echo $MY_SECRET
    # steps:
    #   - name: Check out code
    #     uses: actions/checkout@v2

    #   - name: Log in to Docker Hub
    #     if: contains(github.event.head_commit.message, 'push-image')
    #     uses: docker/login-action@v1 
    #     with:
    #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    #   - name: Build and push Docker image
    #     if: contains(github.event.head_commit.message, 'push-image')
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       push: true
    #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-api:latest
